[package]
name = "meteor-bot"
version = "0.1.0"
edition = "2024"
description = "Meteor's Discord bot."
authors = ["Big Iron"]
repository = "https://github.com/MeteorDevelopment/meteor-bot"
license = "GPL-3.0-only"
keywords = ["discord", "discord-bot", "poise", "bot"]
categories = ["network-programming"]

[dependencies]
anyhow = "1.0"
axum = "0.8"
chrono = "0.4"
dotenvy = "0.15"
envy = "0.4"
humantime = "2.3"
poise = "0.6"
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = ["query", "json", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.21"
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false
strip = true
